import type { Metadata } from "next";
import "./globals.css";
import { urbanist } from "./_assets/fonts";
import cn from "./_utils/cn";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(urbanist.className, "text-x-green")}>{children}</body>
    </html>
  );
}
